// src/seeds/seed-countries.ts
import { CountriesDialCode } from 'src/modules/constants/entities/countries-dial-code.entity';
import { AppDataSource } from '../data-source';

export async function seedCountriesDialCode() {
  const countryRepo = AppDataSource.getRepository(CountriesDialCode);
  console.log("Start save countries..");
  const countries = [
    { name: 'Afghanistan', dial_code: '+93', iso_code: 'AF', flag: '🇦🇫' },
    { name: 'Albania', dial_code: '+355', iso_code: 'AL', flag: '🇦🇱' },
    { name: 'Algeria', dial_code: '+213', iso_code: 'DZ', flag: '🇩🇿' },
    { name: 'Andorra', dial_code: '+376', iso_code: 'AD', flag: '🇦🇩' },
    { name: 'Angola', dial_code: '+244', iso_code: 'AO', flag: '🇦🇴' },
    { name: 'Argentina', dial_code: '+54', iso_code: 'AR', flag: '🇦🇷' },
    { name: 'Armenia', dial_code: '+374', iso_code: 'AM', flag: '🇦🇲' },
    { name: 'Australia', dial_code: '+61', iso_code: 'AU', flag: '🇦🇺' },
    { name: 'Austria', dial_code: '+43', iso_code: 'AT', flag: '🇦🇹' },
    { name: 'Azerbaijan', dial_code: '+994', iso_code: 'AZ', flag: '🇦🇿' },
    { name: 'Bahrain', dial_code: '+973', iso_code: 'BH', flag: '🇧🇭' },
    { name: 'Bangladesh', dial_code: '+880', iso_code: 'BD', flag: '🇧🇩' },
    { name: 'Belarus', dial_code: '+375', iso_code: 'BY', flag: '🇧🇾' },
    { name: 'Belgium', dial_code: '+32', iso_code: 'BE', flag: '🇧🇪' },
    { name: 'Belize', dial_code: '+501', iso_code: 'BZ', flag: '🇧🇿' },
    { name: 'Benin', dial_code: '+229', iso_code: 'BJ', flag: '🇧🇯' },
    { name: 'Bhutan', dial_code: '+975', iso_code: 'BT', flag: '🇧🇹' },
    { name: 'Bolivia', dial_code: '+591', iso_code: 'BO', flag: '🇧🇴' },
    {
      name: 'Bosnia and Herzegovina',
      dial_code: '+387',
      iso_code: 'BA',
      flag: '🇧🇦',
    },
    { name: 'Botswana', dial_code: '+267', iso_code: 'BW', flag: '🇧🇼' },
    { name: 'Brazil', dial_code: '+55', iso_code: 'BR', flag: '🇧🇷' },
    { name: 'Brunei', dial_code: '+673', iso_code: 'BN', flag: '🇧🇳' },
    { name: 'Bulgaria', dial_code: '+359', iso_code: 'BG', flag: '🇧🇬' },
    { name: 'Burkina Faso', dial_code: '+226', iso_code: 'BF', flag: '🇧🇫' },
    { name: 'Burundi', dial_code: '+257', iso_code: 'BI', flag: '🇧🇮' },
    { name: 'Cambodia', dial_code: '+855', iso_code: 'KH', flag: '🇰🇭' },
    { name: 'Cameroon', dial_code: '+237', iso_code: 'CM', flag: '🇨🇲' },
    { name: 'Canada', dial_code: '+1', iso_code: 'CA', flag: '🇨🇦' },
    { name: 'Chad', dial_code: '+235', iso_code: 'TD', flag: '🇹🇩' },
    { name: 'Chile', dial_code: '+56', iso_code: 'CL', flag: '🇨🇱' },
    { name: 'China', dial_code: '+86', iso_code: 'CN', flag: '🇨🇳' },
    { name: 'Colombia', dial_code: '+57', iso_code: 'CO', flag: '🇨🇴' },
    { name: 'Comoros', dial_code: '+269', iso_code: 'KM', flag: '🇰🇲' },
    {
      name: 'Congo (Brazzaville)',
      dial_code: '+242',
      iso_code: 'CG',
      flag: '🇨🇬',
    },
    { name: 'Congo (Kinshasa)', dial_code: '+243', iso_code: 'CD', flag: '🇨🇩' },
    { name: 'Costa Rica', dial_code: '+506', iso_code: 'CR', flag: '🇨🇷' },
    { name: 'Croatia', dial_code: '+385', iso_code: 'HR', flag: '🇭🇷' },
    { name: 'Cuba', dial_code: '+53', iso_code: 'CU', flag: '🇨🇺' },
    { name: 'Cyprus', dial_code: '+357', iso_code: 'CY', flag: '🇨🇾' },
    { name: 'Czech Republic', dial_code: '+420', iso_code: 'CZ', flag: '🇨🇿' },
    { name: 'Denmark', dial_code: '+45', iso_code: 'DK', flag: '🇩🇰' },
    { name: 'Djibouti', dial_code: '+253', iso_code: 'DJ', flag: '🇩🇯' },
    { name: 'Dominican Republic', dial_code: '+1', iso_code: 'DO', flag: '🇩🇴' },
    { name: 'Ecuador', dial_code: '+593', iso_code: 'EC', flag: '🇪🇨' },
    { name: 'El Salvador', dial_code: '+503', iso_code: 'SV', flag: '🇸🇻' },
    { name: 'Estonia', dial_code: '+372', iso_code: 'EE', flag: '🇪🇪' },
    { name: 'Ethiopia', dial_code: '+251', iso_code: 'ET', flag: '🇪🇹' },
    { name: 'Finland', dial_code: '+358', iso_code: 'FI', flag: '🇫🇮' },
    { name: 'France', dial_code: '+33', iso_code: 'FR', flag: '🇫🇷' },
    { name: 'Gabon', dial_code: '+241', iso_code: 'GA', flag: '🇬🇦' },
    { name: 'Gambia', dial_code: '+220', iso_code: 'GM', flag: '🇬🇲' },
    { name: 'Georgia', dial_code: '+995', iso_code: 'GE', flag: '🇬🇪' },
    { name: 'Ghana', dial_code: '+233', iso_code: 'GH', flag: '🇬🇭' },
    { name: 'Greece', dial_code: '+30', iso_code: 'GR', flag: '🇬🇷' },
    { name: 'Guatemala', dial_code: '+502', iso_code: 'GT', flag: '🇬🇹' },
    { name: 'Guinea', dial_code: '+224', iso_code: 'GN', flag: '🇬🇳' },
    { name: 'Honduras', dial_code: '+504', iso_code: 'HN', flag: '🇭🇳' },
    { name: 'Hungary', dial_code: '+36', iso_code: 'HU', flag: '🇭🇺' },
    { name: 'Iceland', dial_code: '+354', iso_code: 'IS', flag: '🇮🇸' },
    { name: 'India', dial_code: '+91', iso_code: 'IN', flag: '🇮🇳' },
    { name: 'Indonesia', dial_code: '+62', iso_code: 'ID', flag: '🇮🇩' },
    { name: 'Iran', dial_code: '+98', iso_code: 'IR', flag: '🇮🇷' },
    { name: 'Iraq', dial_code: '+964', iso_code: 'IQ', flag: '🇮🇶' },
    { name: 'Ireland', dial_code: '+353', iso_code: 'IE', flag: '🇮🇪' },
    { name: 'Israel', dial_code: '+972', iso_code: 'IL', flag: '🇮🇱' },
    { name: 'Italy', dial_code: '+39', iso_code: 'IT', flag: '🇮🇹' },
    { name: 'Japan', dial_code: '+81', iso_code: 'JP', flag: '🇯🇵' },
    { name: 'Kenya', dial_code: '+254', iso_code: 'KE', flag: '🇰🇪' },
    { name: 'Kuwait', dial_code: '+965', iso_code: 'KW', flag: '🇰🇼' },
    { name: 'Lebanon', dial_code: '+961', iso_code: 'LB', flag: '🇱🇧' },
    { name: 'Libya', dial_code: '+218', iso_code: 'LY', flag: '🇱🇾' },
    { name: 'Malaysia', dial_code: '+60', iso_code: 'MY', flag: '🇲🇾' },
    { name: 'Maldives', dial_code: '+960', iso_code: 'MV', flag: '🇲🇻' },
    { name: 'Mexico', dial_code: '+52', iso_code: 'MX', flag: '🇲🇽' },
    { name: 'Morocco', dial_code: '+212', iso_code: 'MA', flag: '🇲🇦' },
    { name: 'Nepal', dial_code: '+977', iso_code: 'NP', flag: '🇳🇵' },
    { name: 'Netherlands', dial_code: '+31', iso_code: 'NL', flag: '🇳🇱' },
    { name: 'New Zealand', dial_code: '+64', iso_code: 'NZ', flag: '🇳🇿' },
    { name: 'Nigeria', dial_code: '+234', iso_code: 'NG', flag: '🇳🇬' },
    { name: 'Norway', dial_code: '+47', iso_code: 'NO', flag: '🇳🇴' },
    { name: 'Oman', dial_code: '+968', iso_code: 'OM', flag: '🇴🇲' },
    { name: 'Pakistan', dial_code: '+92', iso_code: 'PK', flag: '🇵🇰' },
    { name: 'Philippines', dial_code: '+63', iso_code: 'PH', flag: '🇵🇭' },
    { name: 'Poland', dial_code: '+48', iso_code: 'PL', flag: '🇵🇱' },
    { name: 'Portugal', dial_code: '+351', iso_code: 'PT', flag: '🇵🇹' },
    { name: 'Qatar', dial_code: '+974', iso_code: 'QA', flag: '🇶🇦' },
    { name: 'Romania', dial_code: '+40', iso_code: 'RO', flag: '🇷🇴' },
    { name: 'Russia', dial_code: '+7', iso_code: 'RU', flag: '🇷🇺' },
    { name: 'Saudi Arabia', dial_code: '+966', iso_code: 'SA', flag: '🇸🇦' },
    { name: 'Senegal', dial_code: '+221', iso_code: 'SN', flag: '🇸🇳' },
    { name: 'Serbia', dial_code: '+381', iso_code: 'RS', flag: '🇷🇸' },
    { name: 'Singapore', dial_code: '+65', iso_code: 'SG', flag: '🇸🇬' },
    { name: 'Slovakia', dial_code: '+421', iso_code: 'SK', flag: '🇸🇰' },
    { name: 'Slovenia', dial_code: '+386', iso_code: 'SI', flag: '🇸🇮' },
    { name: 'Somalia', dial_code: '+252', iso_code: 'SO', flag: '🇸🇴' },
    { name: 'South Africa', dial_code: '+27', iso_code: 'ZA', flag: '🇿🇦' },
    { name: 'South Korea', dial_code: '+82', iso_code: 'KR', flag: '🇰🇷' },
    { name: 'Spain', dial_code: '+34', iso_code: 'ES', flag: '🇪🇸' },
    { name: 'Sri Lanka', dial_code: '+94', iso_code: 'LK', flag: '🇱🇰' },
    { name: 'Sudan', dial_code: '+249', iso_code: 'SD', flag: '🇸🇩' },
    { name: 'Sweden', dial_code: '+46', iso_code: 'SE', flag: '🇸🇪' },
    { name: 'Switzerland', dial_code: '+41', iso_code: 'CH', flag: '🇨🇭' },
    { name: 'Syria', dial_code: '+963', iso_code: 'SY', flag: '🇸🇾' },
    { name: 'Thailand', dial_code: '+66', iso_code: 'TH', flag: '🇹🇭' },
    { name: 'Tunisia', dial_code: '+216', iso_code: 'TN', flag: '🇹🇳' },
    { name: 'Turkey', dial_code: '+90', iso_code: 'TR', flag: '🇹🇷' },
    { name: 'Ukraine', dial_code: '+380', iso_code: 'UA', flag: '🇺🇦' },
    {
      name: 'United Arab Emirates',
      dial_code: '+971',
      iso_code: 'AE',
      flag: '🇦🇪',
    },
    { name: 'Uruguay', dial_code: '+598', iso_code: 'UY', flag: '🇺🇾' },
    { name: 'Uzbekistan', dial_code: '+998', iso_code: 'UZ', flag: '🇺🇿' },
    { name: 'Venezuela', dial_code: '+58', iso_code: 'VE', flag: '🇻🇪' },
    { name: 'Vietnam', dial_code: '+84', iso_code: 'VN', flag: '🇻🇳' },
    { name: 'Yemen', dial_code: '+967', iso_code: 'YE', flag: '🇾🇪' },
    { name: 'Zambia', dial_code: '+260', iso_code: 'ZM', flag: '🇿🇲' },
    { name: 'Zimbabwe', dial_code: '+263', iso_code: 'ZW', flag: '🇿🇼' },
    { name: 'Palestine', dial_code: '+970', iso_code: 'PS', flag: '🇵🇸' },
    { name: 'Jordan', dial_code: '+962', iso_code: 'JO', flag: '🇯🇴' },
    { name: 'Egypt', dial_code: '+20', iso_code: 'EG', flag: '🇪🇬' },
    { name: 'United States', dial_code: '+1', iso_code: 'US', flag: '🇺🇸' },
    { name: 'Germany', dial_code: '+49', iso_code: 'DE', flag: '🇩🇪' },
    { name: 'United Kingdom', dial_code: '+44', iso_code: 'GB', flag: '🇬🇧' },
  ];

  for (const country of countries) {
    const existing = await countryRepo.findOneBy({
      iso_code: country.iso_code,
    });

    if (!existing) {
      const newCountry = countryRepo.create(country);
      await countryRepo.save(newCountry);
      console.log(`✔️ Seeded ${country.name}`);
    } else {
      console.log(`⚠️ ${country.name} already exists.`);
    }
  }
}
